apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops-tools
spec:
  selector:
    app: nexus-server
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32000